documentation:
- all: ['README.md']
new package:
- 'packages/**'
custom-scripts:
- 'custom_scripts/**'
automation-core:
- 'automation.ps1'
- 'YamlCreate/YamlCreate.ps1'
- '.github/**'
add-contributor:
- all: ['README.md','.all-contributorsrc']
