version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "19"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/vedantmgoyal2009/vedantmgoyal2009"