version = 1

exclude_patterns = [
  "sheltasks-cli/_sysroots",
  "CODE_OF_CONDUCT.md",
  "LICENSE",
  "package-lock.json",
  "tsconfig.json",
  "vercel.json"
]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "19"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/vedantmgoyal2009/vedantmgoyal2009/sheltasks-cli"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "gofumpt"