name: Fetch All Versions
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.5
      - name: Run automation script
        shell: pwsh
        run: ./fetch-all-versions.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.MYSUPERSECRETINFORMATION }}
