name: Fetch Old Versions
on:
  workflow_dispatch:
    inputs:
      pkgid:
        required: true
        description: PackageIdentifier
        type: string
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run FetchOldVersions.ps1
        shell: pwsh
        run: Set-Location .\scripts; .\FetchOldVersions.ps1 -currentUpdate ${{ github.event.inputs.pkgid }}
        env:
          GITHUB_TOKEN: ${{ secrets.MYSUPERSECRETINFORMATION }}
