# This is a basic workflow to help you get started with Actions

name: Validate JSON

# Triggers the workflow on push or pull request events
on: [push, pull_request]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: JSON validation
        shell: pwsh
        run: |
          $packages = Get-ChildItem .\packages\ -Recurse -File | Select-Object -Property Name,FullName
          foreach ($json in $packages) {
              $package = Get-Content -Raw -Path $json.FullName
              if ((Test-Json -Json $package -SchemaFile ./schema.json) -eq $false) {
                  $jsonWithError += @($json.Name)
              }
          }
          if ($jsonWithError.Count -gt 0) {
              Clear-Host
              Write-Host -ForegroundColor Red "The following packages have errors:"
              foreach ($i in $jsonWithError) {
                  Write-Host -ForegroundColor Red "   $i" # Added spaces for indentation
              }
              exit 1
          }
          else
          {
              Write-Host -ForegroundColor Green "All packages are valid!"
          }
